import { Plugin } from 'vite'
import * as fs from 'node:fs'
import * as path from 'node:path'

const RESUMES_DIR = path.resolve(process.cwd(), 'resumes')
const GENERATED = path.resolve(process.cwd(), 'src/generated/resumes.ts')

function findResumeVariants(): string[] {
  if (!fs.existsSync(RESUMES_DIR)) return []
  return fs
    .readdirSync(RESUMES_DIR)
    .filter((name) => !name.startsWith('_') && !name.startsWith('.'))
    .filter((name) => fs.statSync(path.join(RESUMES_DIR, name)).isDirectory())
    .filter((name) => fs.existsSync(path.join(RESUMES_DIR, name, 'index.tsx')))
}

function generateRegistry(variants: string[]): string {
  const imports = variants
    .map((v) => {
      const safe = v.replace(/-/g, '_')
      return `import _${safe}_default from '../../resumes/${v}/index'\nimport { meta as _${safe}_meta } from '../../resumes/${v}/meta'`
    })
    .join('\n')

  const entries = variants
    .map((v) => {
      const safe = v.replace(/-/g, '_')
      return `  '${v}': { default: _${safe}_default, meta: _${safe}_meta },`
    })
    .join('\n')

  return `// generated by sync-resumes-plugin.ts and scripts/sync-resumes.mjs - do not edit
import type { ResumeModule } from '@/lib/resume-registry'
${imports}

export const resumes: Record<string, ResumeModule> = {
${entries}
}
`
}

function syncOnce() {
  const variants = findResumeVariants()
  fs.mkdirSync(path.dirname(GENERATED), { recursive: true })
  fs.writeFileSync(GENERATED, generateRegistry(variants))
}

export function syncResumesPlugin(): Plugin {
  return {
    name: 'resumex-sync-resumes',
    enforce: 'pre',
    buildStart() {
      syncOnce()
    },
    configureServer(server) {
      syncOnce()
      server.watcher.add(RESUMES_DIR)
      server.watcher.on('add', (file) => {
        if (file.startsWith(RESUMES_DIR)) syncOnce()
      })
      server.watcher.on('unlink', (file) => {
        if (file.startsWith(RESUMES_DIR)) syncOnce()
      })
    },
  }
}
