import { Plugin } from 'vite'
import * as fs from 'node:fs'
import * as path from 'node:path'

const TEMPLATES_DIR = path.resolve(process.cwd(), 'templates')
const GENERATED = path.resolve(process.cwd(), 'src/generated/templates.ts')
const MANIFEST = path.resolve(process.cwd(), 'public/templates.json')

function findTemplateIds(): string[] {
  if (!fs.existsSync(TEMPLATES_DIR)) return []
  return fs
    .readdirSync(TEMPLATES_DIR)
    .filter((name) => !name.startsWith('_') && !name.startsWith('.'))
    .filter((name) => fs.statSync(path.join(TEMPLATES_DIR, name)).isDirectory())
    .filter((name) => fs.existsSync(path.join(TEMPLATES_DIR, name, 'index.tsx')))
}

function generateRegistry(ids: string[]): string {
  const imports = ids
    .map(
      (id) =>
        `import _${id.replace(/-/g, '_')}_default from '../../templates/${id}/index'\nimport { meta as _${id.replace(
          /-/g,
          '_',
        )}_meta } from '../../templates/${id}/meta'`,
    )
    .join('\n')

  const entries = ids
    .map(
      (id) =>
        `  '${id}': { default: _${id.replace(/-/g, '_')}_default, meta: _${id.replace(
          /-/g,
          '_',
        )}_meta },`,
    )
    .join('\n')

  return `// generated by sync-templates-plugin.ts — do not edit
import type { TemplateModule } from '@/lib/template-registry'
${imports}

export const templates: Record<string, TemplateModule> = {
${entries}
}
`
}

export function readMetaFromFile(_id: string): unknown | null {
  // best effort — read meta.ts and find the exported `meta` literal via
  // dynamic import won't work in plugin context; we use a lightweight regex
  // because `meta.ts` is a small declarative file by convention
  // we can't safely eval TS here; the manifest is best read via the runtime
  // app's listTemplates(). For build-time manifest, we instead read a JSON
  // sidecar if present, or fall back to id-only.
  return null
}

function writeManifest(ids: string[]) {
  const manifest = ids.map((id) => ({ id }))
  fs.mkdirSync(path.dirname(MANIFEST), { recursive: true })
  fs.writeFileSync(MANIFEST, JSON.stringify(manifest, null, 2))
}

function syncOnce() {
  const ids = findTemplateIds()
  fs.mkdirSync(path.dirname(GENERATED), { recursive: true })
  fs.writeFileSync(GENERATED, generateRegistry(ids))
  writeManifest(ids)
}

export function syncTemplatesPlugin(): Plugin {
  return {
    name: 'resumex-sync-templates',
    enforce: 'pre',
    buildStart() {
      syncOnce()
    },
    configureServer(server) {
      syncOnce()
      server.watcher.add(TEMPLATES_DIR)
      server.watcher.on('add', (file) => {
        if (file.startsWith(TEMPLATES_DIR)) syncOnce()
      })
      server.watcher.on('unlink', (file) => {
        if (file.startsWith(TEMPLATES_DIR)) syncOnce()
      })
    },
  }
}
