/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as VariantRouteImport } from './routes/$variant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewTemplateIdRouteImport } from './routes/preview.$templateId'
import { Route as VariantPrintRouteImport } from './routes/$variant.print'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const VariantRoute = VariantRouteImport.update({
  id: '/$variant',
  path: '/$variant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewTemplateIdRoute = PreviewTemplateIdRouteImport.update({
  id: '/preview/$templateId',
  path: '/preview/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const VariantPrintRoute = VariantPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => VariantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$variant': typeof VariantRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/$variant/print': typeof VariantPrintRoute
  '/preview/$templateId': typeof PreviewTemplateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$variant': typeof VariantRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/$variant/print': typeof VariantPrintRoute
  '/preview/$templateId': typeof PreviewTemplateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$variant': typeof VariantRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/$variant/print': typeof VariantPrintRoute
  '/preview/$templateId': typeof PreviewTemplateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$variant'
    | '/templates'
    | '/$variant/print'
    | '/preview/$templateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$variant'
    | '/templates'
    | '/$variant/print'
    | '/preview/$templateId'
  id:
    | '__root__'
    | '/'
    | '/$variant'
    | '/templates'
    | '/$variant/print'
    | '/preview/$templateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VariantRoute: typeof VariantRouteWithChildren
  TemplatesRoute: typeof TemplatesRoute
  PreviewTemplateIdRoute: typeof PreviewTemplateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$variant': {
      id: '/$variant'
      path: '/$variant'
      fullPath: '/$variant'
      preLoaderRoute: typeof VariantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$templateId': {
      id: '/preview/$templateId'
      path: '/preview/$templateId'
      fullPath: '/preview/$templateId'
      preLoaderRoute: typeof PreviewTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$variant/print': {
      id: '/$variant/print'
      path: '/print'
      fullPath: '/$variant/print'
      preLoaderRoute: typeof VariantPrintRouteImport
      parentRoute: typeof VariantRoute
    }
  }
}

interface VariantRouteChildren {
  VariantPrintRoute: typeof VariantPrintRoute
}

const VariantRouteChildren: VariantRouteChildren = {
  VariantPrintRoute: VariantPrintRoute,
}

const VariantRouteWithChildren =
  VariantRoute._addFileChildren(VariantRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VariantRoute: VariantRouteWithChildren,
  TemplatesRoute: TemplatesRoute,
  PreviewTemplateIdRoute: PreviewTemplateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
